[package]
name = "dh-middleman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8"
clap = "3.0"
num-bigint = "0.4"
num-traits = "0.2"
